### ISSUE TITLE
Potential deduplication bug on ControlChange events

### ISSUE THREAD

**Issue by gudgud96** [YatingMusic/miditoolkit#24]
In `midi/parser.py` there is this code:

https://github.com/YatingMusic/miditoolkit/blob/9835be29e42fbc23529d61273820707ccfa189f4/miditoolkit/midi/parser.py#L565-L578

It will traverse `control_change` events, and remove consecutive events with the same value, regardless of the control number.

However, this is not ideal for some cases, for example: a lot of tracks use Registered Parameter Number (RPN) to set the pitch bend range (see [reference](https://www.recordingblogs.com/wiki/midi-registered-parameter-number-rpn)). It will require a consecutive pair of `ControlChange(control=0x65, value=0x00), ControlChange(control=0x64, value=0x00)` to notify the controller about an incoming pitch bend range message. The code above will remove these RPN events, resulting in information loss.

Is this code really needed? If not, I might suggest removing them to preserve all the `control_change` events as-is.

**Comment by Natooz** [comment]
Hello 👋,

I'm taking over and doing some fixes in the lib.
Nice catch! I don't know what was the initial purpose of this deduplication, however I stand with you that it might be preferable to remove it. Ultimately, when saving a MIDI, all its content should be written unchanged as would a user want.

It has been some time since you opened this. Would you be interested in opening a PR that would comment it, to claim authorship of the fix?
Otherwise I'll do it myself in a couple of days.

**Comment by gudgud96** [comment]
Hi @Natooz,

Thanks for taking on the mantle! 

Yes I can open a PR for this in the next couple of days.
